/**
 * The SRD spell dataset. The verified core is the canonical Fireball fixture
 * (surfaced via slice.ts); the remaining ~338 spells are ingested to qa:draft —
 * their structured meta + verbatim text validate against the contracts schema,
 * but their `plain` sentence and `effects[]` await the rules-lawyer pass, so the
 * loader keeps them out of real sessions (dev only) until verified.
 *
 * The draft records are committed data (spells.draft.json), regenerated by the
 * ingestion driver (`npm run ingest`) from the raw SRD extraction — so the
 * shipped library does no runtime filesystem I/O, and the data can't drift from
 * the pipeline that makes it (a golden test re-runs the pipeline and compares).
 */
import { RulesEntitySchema, type RulesEntity } from '@questra/contracts';
import { FIREBALL } from './slice.js';
import draftRecords from './spells.draft.json' with { type: 'json' };

/** Ids already present as verified entities — excluded from the draft set to avoid duplicates. */
const VERIFIED_SPELL_IDS = new Set<string>([FIREBALL.id]);

/** The ~338 draft spells (everything ingested except the verified core), validated against the schema. */
export const DRAFT_SPELLS: RulesEntity[] = (draftRecords as unknown[])
  .map((r) => RulesEntitySchema.parse(r))
  .filter((s) => !VERIFIED_SPELL_IDS.has(s.id));

/** Backwards-friendly accessor. */
export function draftSpells(): RulesEntity[] {
  return DRAFT_SPELLS;
}
